# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hi": "01_core.ipynb"}

modules = ["tutorial.py",
           "core.py"]

doc_url = "https://fastai.github.io/nbdev_metatuto/"

git_url = "https://github.com/fastai/nbdev_metatuto/tree/master/"

def custom_doc_links(name): return None
