# AUTOGENERATED! DO NOT EDIT! File to edit: 00_tutorial.ipynb (unless otherwise specified).

__all__ = ['say_hi', 'SoothSayer', 'SoothSayer']

# Cell
def say_hi(to):
    "Enthusiastically say hi to someone"
    return f'Hii {to}!'

# Cell
class SoothSayer:
    "Yell hi at someone until they are annoyed enough to either reply or flee"
    def __init__(self,to): self.to = to
    def say(self): return say_hi(self.to)

# Cell
class SoothSayer:
    "Yell hi at someone until they are annoyed enough to either reply or flee"
    def __init__(self,to): self.to = to
    def say(self):
        "Do your thing, stalker!"
        return say_hi(self.to)